CREATE USER dex WITH PASSWORD '66964843358242dbaaa7778d8477c288';
CREATE DATABASE dex_db;
GRANT CONNECT ON DATABASE dex_db TO dex;

CREATE USER vizual WITH PASSWORD 'password';
CREATE DATABASE vizual_db;
GRANT ALL PRIVILEGES ON DATABASE vizual_db TO vizual;
