name: Build and Publish
on:
# run it on push to the default repository branch
  push:
    paths-ignore:
      - 'charts/**'
      - '**.md'
      - 'dockerfiles/postgres/**'
      - 'scripts/**'
    branches: [main]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: vizual-app

jobs:
# define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
# run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfiles/vizual/Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/vizual:latest
    - name: Docker push
      run: |
        docker login ${{ env.REGISTRY }} -u jebinjeb -p ${{ secrets.GITHUB_TOKEN }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/vizual:latest
